pygments:     true
markdown:     rdiscount
permalink:    /posts/:year-:month-:day-:title.html
title:        Snail
description:  Snail个人博客
keywords:     Snail, Simpleyyt
author:       Snail
email:        simpleyyt@gmail.com
github:       http://github.com/simpleyyt
